version: "3.8"

services:
  hubfly:
    build: .
    container_name: hubfly-reverse-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - hubfly_proxy_data:/etc/hubfly
      - hubfly_proxy_certs:/etc/letsencrypt
      - hubfly_proxy_webroot:/var/www/hubfly
      - ./static:/var/www/hubfly/static
      - ./templates:/etc/hubfly/templates
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC

volumes:
  hubfly_proxy_data:
    name: hubfly_proxy_data
  hubfly_proxy_certs:
    name: hubfly_proxy_certs
  hubfly_proxy_webroot:
    name: hubfly_proxy_webroot
